/* Generated by re2c 3.0 on Thu Aug  3 16:04:51 2023 */
#line 1 "/home/cadence/projects/Mint/source/scan/Scanner.re"
// Copyright (C) 2023 Cade Weinberg
//
// This file is part of Mint.
//
// Mint is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Mint is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Mint.  If not, see <http://www.gnu.org/licenses/>.

#include "scan/Scanner.hpp"

namespace mint {
void Scanner::UpdateLocation() noexcept {
  auto length = cursor - token;
  location.fline = location.lline;
  location.fcolumn = location.lcolumn;

  for (std::ptrdiff_t i = 0; i < length; ++i) {
    if (token[i] == '\n') {
      ++location.lline;
      location.lcolumn = 0;
      location.fcolumn = 0;
    } else {
      ++location.lcolumn;
    }
  }
}

Scanner::Scanner() noexcept : location{1, 0, 1, 0} {
  end = marker = token = cursor = buffer.end();
}

Scanner::Scanner(std::string_view input) noexcept
    : location{1, 0, 1, 0}, buffer{input} {
  end = buffer.end();
  marker = token = cursor = buffer.begin();
}

auto Scanner::view() const noexcept -> std::string_view {
  return {buffer.c_str(), buffer.size()};
}

void Scanner::reset() noexcept {
  location = {1, 0, 1, 0};
  buffer.clear();
  end = cursor = marker = token = buffer.end();
}

auto Scanner::endOfInput() const noexcept -> bool { return cursor == end; }

void Scanner::append(std::string_view text) noexcept {
  if (buffer.empty()) {
    buffer.append(text);
    end = buffer.end();
    marker = token = cursor = buffer.begin();
  } else {
    auto begin = buffer.begin();
    auto cursor_offset = std::distance(begin, cursor);
    auto marker_offset = std::distance(begin, marker);
    auto token_offset = std::distance(begin, token);

    buffer.append(text);

    begin = buffer.begin();
    end = buffer.end();
    cursor = begin + cursor_offset;
    marker = begin + marker_offset;
    token = begin + token_offset;
  }
}

auto Scanner::getText() const noexcept -> std::string_view {
  return {token, cursor};
}

auto Scanner::getLocation() const noexcept -> Location { return location; }

#line 110 "/home/cadence/projects/Mint/source/scan/Scanner.re"

// NOLINTBEGIN(cppcoreguidelines-avoid-goto)
// #REASON: re2c uses gotos to implement the lexer and as all of the
// gotos are from generated code we are trusting re2c to
// use gotos in a safe and sane way here.

auto Scanner::scan() noexcept -> Token {
  while (true) {
    token = cursor;
    
#line 100 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
{
	char yych;
	unsigned int yyaccept = 0;
	yych = *cursor;
	switch (yych) {
		case '\t':
		case '\n':
		case ' ': goto yy3;
		case '!': goto yy5;
		case '"': goto yy7;
		case '%': goto yy8;
		case '&': goto yy9;
		case '(': goto yy10;
		case ')': goto yy11;
		case '*': goto yy12;
		case '+': goto yy13;
		case ',': goto yy14;
		case '-': goto yy15;
		case '/': goto yy17;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy18;
		case ':': goto yy20;
		case ';': goto yy22;
		case '<': goto yy23;
		case '=': goto yy25;
		case '>': goto yy27;
		case 'A':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'o':
		case 'q':
		case 'r':
		case 's':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy29;
		case 'B': goto yy32;
		case 'I': goto yy33;
		case 'N': goto yy34;
		case '\\': goto yy35;
		case 'f': goto yy36;
		case 'i': goto yy37;
		case 'l': goto yy38;
		case 'm': goto yy39;
		case 'n': goto yy40;
		case 'p': goto yy41;
		case 't': goto yy42;
		case '{': goto yy43;
		case '|': goto yy44;
		case '}': goto yy45;
		default:
			if (end <= cursor) goto yy119;
			goto yy1;
	}
yy1:
	++cursor;
yy2:
#line 165 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Error; }
#line 201 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy3:
	yych = *++cursor;
	switch (yych) {
		case '\t':
		case '\n':
		case ' ': goto yy3;
		default: goto yy4;
	}
yy4:
#line 164 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); continue; }
#line 213 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy5:
	yych = *++cursor;
	switch (yych) {
		case '=': goto yy46;
		default: goto yy6;
	}
yy6:
#line 150 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Not; }
#line 223 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy7:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '\n':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~': goto yy48;
		default: goto yy2;
	}
yy8:
	++cursor;
#line 149 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Modulo; }
#line 329 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy9:
	++cursor;
#line 151 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::And; }
#line 334 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy10:
	++cursor;
#line 138 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::BeginParen; }
#line 339 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy11:
	++cursor;
#line 139 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::EndParen; }
#line 344 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy12:
	++cursor;
#line 147 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Star; }
#line 349 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy13:
	++cursor;
#line 145 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Plus; }
#line 354 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy14:
	++cursor;
#line 137 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Comma; }
#line 359 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy15:
	yych = *++cursor;
	switch (yych) {
		case '>': goto yy51;
		default: goto yy16;
	}
yy16:
#line 146 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Minus; }
#line 369 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy17:
	++cursor;
#line 148 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Divide; }
#line 374 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy18:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy18;
		default: goto yy19;
	}
yy19:
#line 161 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Integer; }
#line 393 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy20:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case ':': goto yy52;
		default: goto yy21;
	}
yy21:
#line 136 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Colon; }
#line 404 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy22:
	++cursor;
#line 135 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Semicolon; }
#line 409 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy23:
	yych = *++cursor;
	switch (yych) {
		case '=': goto yy53;
		default: goto yy24;
	}
yy24:
#line 153 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::LessThan; }
#line 419 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy25:
	yych = *++cursor;
	switch (yych) {
		case '=': goto yy54;
		default: goto yy26;
	}
yy26:
#line 134 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Equal; }
#line 429 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy27:
	yych = *++cursor;
	switch (yych) {
		case '=': goto yy55;
		default: goto yy28;
	}
yy28:
#line 157 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::GreaterThan; }
#line 439 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy29:
	yyaccept = 2;
	yych = *(marker = ++cursor);
yy30:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy29;
		case ':': goto yy56;
		default: goto yy31;
	}
yy31:
#line 160 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Identifier; }
#line 514 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy32:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'o': goto yy57;
		default: goto yy30;
	}
yy33:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'n': goto yy58;
		default: goto yy30;
	}
yy34:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'i': goto yy59;
		default: goto yy30;
	}
yy35:
	++cursor;
#line 142 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::BSlash; }
#line 543 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy36:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'a': goto yy60;
		case 'r': goto yy61;
		default: goto yy30;
	}
yy37:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'm': goto yy62;
		default: goto yy30;
	}
yy38:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'e': goto yy63;
		default: goto yy30;
	}
yy39:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'o': goto yy64;
		default: goto yy30;
	}
yy40:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'i': goto yy65;
		default: goto yy30;
	}
yy41:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'r': goto yy66;
		case 'u': goto yy67;
		default: goto yy30;
	}
yy42:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'r': goto yy68;
		default: goto yy30;
	}
yy43:
	++cursor;
#line 140 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::BeginBrace; }
#line 606 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy44:
	++cursor;
#line 152 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Or; }
#line 611 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy45:
	++cursor;
#line 141 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::EndBrace; }
#line 616 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy46:
	++cursor;
#line 156 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::NotEqual; }
#line 621 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy47:
	yych = *++cursor;
yy48:
	switch (yych) {
		case '\n':
		case '!':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~': goto yy47;
		case '"': goto yy50;
		default: goto yy49;
	}
yy49:
	cursor = marker;
	switch (yyaccept) {
		case 0: goto yy2;
		case 1: goto yy21;
		case 2: goto yy31;
		case 3: goto yy73;
		case 4: goto yy78;
		case 5: goto yy81;
		case 6: goto yy89;
		case 7: goto yy95;
		case 8: goto yy99;
		case 9: goto yy107;
		case 10: goto yy109;
		case 11: goto yy112;
		case 12: goto yy114;
		case 13: goto yy116;
		default: goto yy118;
	}
yy50:
	++cursor;
#line 162 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Text; }
#line 746 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy51:
	++cursor;
#line 143 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::RArrow; }
#line 751 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy52:
	yych = *++cursor;
	switch (yych) {
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy29;
		default: goto yy49;
	}
yy53:
	++cursor;
#line 154 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::LessThanOrEqual; }
#line 814 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy54:
	++cursor;
#line 155 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::EqualEqual; }
#line 819 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy55:
	++cursor;
#line 158 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::GreaterThanOrEqual; }
#line 824 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy56:
	yych = *++cursor;
	switch (yych) {
		case ':': goto yy69;
		default: goto yy49;
	}
yy57:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'o': goto yy70;
		default: goto yy30;
	}
yy58:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 't': goto yy71;
		default: goto yy30;
	}
yy59:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'l': goto yy72;
		default: goto yy30;
	}
yy60:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'l': goto yy74;
		default: goto yy30;
	}
yy61:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'o': goto yy75;
		default: goto yy30;
	}
yy62:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'p': goto yy76;
		default: goto yy30;
	}
yy63:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 't': goto yy77;
		default: goto yy30;
	}
yy64:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'd': goto yy79;
		default: goto yy30;
	}
yy65:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'l': goto yy80;
		default: goto yy30;
	}
yy66:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'i': goto yy82;
		default: goto yy30;
	}
yy67:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'b': goto yy83;
		default: goto yy30;
	}
yy68:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'u': goto yy84;
		default: goto yy30;
	}
yy69:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy29;
		default: goto yy49;
	}
yy70:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'l': goto yy85;
		default: goto yy30;
	}
yy71:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'e': goto yy86;
		default: goto yy30;
	}
yy72:
	yyaccept = 3;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy73;
	}
yy73:
#line 121 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::NilType; }
#line 1084 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy74:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 's': goto yy87;
		default: goto yy30;
	}
yy75:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'm': goto yy88;
		default: goto yy30;
	}
yy76:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'o': goto yy90;
		default: goto yy30;
	}
yy77:
	yyaccept = 4;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy78;
	}
yy78:
#line 127 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Let; }
#line 1182 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy79:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'u': goto yy91;
		default: goto yy30;
	}
yy80:
	yyaccept = 5;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy81;
	}
yy81:
#line 120 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Nil; }
#line 1264 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy82:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'v': goto yy92;
		default: goto yy30;
	}
yy83:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'l': goto yy93;
		default: goto yy30;
	}
yy84:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'e': goto yy94;
		default: goto yy30;
	}
yy85:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'e': goto yy96;
		default: goto yy30;
	}
yy86:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'g': goto yy97;
		default: goto yy30;
	}
yy87:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'e': goto yy98;
		default: goto yy30;
	}
yy88:
	yyaccept = 6;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy89;
	}
yy89:
#line 132 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::From; }
#line 1386 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy90:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'r': goto yy100;
		default: goto yy30;
	}
yy91:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'l': goto yy101;
		default: goto yy30;
	}
yy92:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'a': goto yy102;
		default: goto yy30;
	}
yy93:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'i': goto yy103;
		default: goto yy30;
	}
yy94:
	yyaccept = 7;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy95;
	}
yy95:
#line 123 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::True; }
#line 1492 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy96:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'a': goto yy104;
		default: goto yy30;
	}
yy97:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'e': goto yy105;
		default: goto yy30;
	}
yy98:
	yyaccept = 8;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy99;
	}
yy99:
#line 124 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::False; }
#line 1582 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy100:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 't': goto yy106;
		default: goto yy30;
	}
yy101:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'e': goto yy108;
		default: goto yy30;
	}
yy102:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 't': goto yy110;
		default: goto yy30;
	}
yy103:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'c': goto yy111;
		default: goto yy30;
	}
yy104:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'n': goto yy113;
		default: goto yy30;
	}
yy105:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'r': goto yy115;
		default: goto yy30;
	}
yy106:
	yyaccept = 9;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy107;
	}
yy107:
#line 131 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Import; }
#line 1704 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy108:
	yyaccept = 10;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy109;
	}
yy109:
#line 128 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Module; }
#line 1778 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy110:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy31;
		case 'e': goto yy117;
		default: goto yy30;
	}
yy111:
	yyaccept = 11;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy112;
	}
yy112:
#line 129 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Public; }
#line 1860 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy113:
	yyaccept = 12;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy114;
	}
yy114:
#line 125 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::BooleanType; }
#line 1934 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy115:
	yyaccept = 13;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy116;
	}
yy116:
#line 122 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::IntegerType; }
#line 2008 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy117:
	yyaccept = 14;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy118;
	}
yy118:
#line 130 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Private; }
#line 2082 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy119:
#line 166 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::End; }
#line 2086 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
}
#line 167 "/home/cadence/projects/Mint/source/scan/Scanner.re"

  }
}
// NOLINTEND(cppcoreguidelines-avoid-goto)
} // namespace mint