/* Generated by re2c 3.0 on Fri Jun 16 17:50:11 2023 */
#line 1 "/home/cadence/projects/Mint/source/scan/Scanner.re"
// Copyright (C) 2023 Cade Weinberg
//
// This file is part of Mint.
//
// Mint is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Mint is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Mint.  If not, see <http://www.gnu.org/licenses/>.

#include "scan/Scanner.hpp"

namespace mint {
#line 41 "/home/cadence/projects/Mint/source/scan/Scanner.re"

// NOLINTBEGIN(cppcoreguidelines-avoid-goto)
// #REASON: re2c uses gotos to implement the lexer and as all of the
// gotos are from generated code we are trusting re2c to
// use gotos in a safe and sane way here.

auto Scanner::scan() noexcept -> Token {
  while (true) {
    token = cursor;
    
#line 35 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
{
	char yych;
	unsigned int yyaccept = 0;
	yych = *cursor;
	switch (yych) {
		case '\t':
		case '\n':
		case ' ': goto yy3;
		case '!': goto yy5;
		case '%': goto yy7;
		case '&': goto yy8;
		case '(': goto yy9;
		case ')': goto yy10;
		case '*': goto yy11;
		case '+': goto yy12;
		case '-': goto yy13;
		case '/': goto yy14;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy15;
		case ':': goto yy17;
		case ';': goto yy18;
		case '<': goto yy19;
		case '=': goto yy21;
		case '>': goto yy23;
		case 'A':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'o':
		case 'q':
		case 'r':
		case 's':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy25;
		case 'B': goto yy28;
		case 'I': goto yy29;
		case 'N': goto yy30;
		case 'f': goto yy31;
		case 'l': goto yy32;
		case 'm': goto yy33;
		case 'n': goto yy34;
		case 'p': goto yy35;
		case 't': goto yy36;
		case '{': goto yy37;
		case '|': goto yy38;
		case '}': goto yy39;
		default:
			if (end <= cursor) goto yy99;
			goto yy1;
	}
yy1:
	++cursor;
yy2:
#line 89 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Error; }
#line 133 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy3:
	yych = *++cursor;
	switch (yych) {
		case '\t':
		case '\n':
		case ' ': goto yy3;
		default: goto yy4;
	}
yy4:
#line 88 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); continue; }
#line 145 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy5:
	yych = *++cursor;
	switch (yych) {
		case '=': goto yy40;
		default: goto yy6;
	}
yy6:
#line 75 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Not; }
#line 155 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy7:
	++cursor;
#line 74 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Modulo; }
#line 160 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy8:
	++cursor;
#line 76 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::And; }
#line 165 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy9:
	++cursor;
#line 65 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::BeginParen; }
#line 170 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy10:
	++cursor;
#line 66 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::EndParen; }
#line 175 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy11:
	++cursor;
#line 72 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Star; }
#line 180 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy12:
	++cursor;
#line 70 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Plus; }
#line 185 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy13:
	++cursor;
#line 71 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Minus; }
#line 190 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy14:
	++cursor;
#line 73 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Divide; }
#line 195 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy15:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy15;
		default: goto yy16;
	}
yy16:
#line 86 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Integer; }
#line 214 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy17:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	switch (yych) {
		case ':': goto yy41;
		default: goto yy2;
	}
yy18:
	++cursor;
#line 64 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Semicolon; }
#line 226 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy19:
	yych = *++cursor;
	switch (yych) {
		case '=': goto yy43;
		default: goto yy20;
	}
yy20:
#line 78 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::LessThan; }
#line 236 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy21:
	yych = *++cursor;
	switch (yych) {
		case '=': goto yy44;
		default: goto yy22;
	}
yy22:
#line 63 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Equal; }
#line 246 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy23:
	yych = *++cursor;
	switch (yych) {
		case '=': goto yy45;
		default: goto yy24;
	}
yy24:
#line 82 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::GreaterThan; }
#line 256 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy25:
	yyaccept = 1;
	yych = *(marker = ++cursor);
yy26:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy25;
		case ':': goto yy46;
		default: goto yy27;
	}
yy27:
#line 85 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Identifier; }
#line 331 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy28:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'o': goto yy47;
		default: goto yy26;
	}
yy29:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'n': goto yy48;
		default: goto yy26;
	}
yy30:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'i': goto yy49;
		default: goto yy26;
	}
yy31:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'a': goto yy50;
		default: goto yy26;
	}
yy32:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'e': goto yy51;
		default: goto yy26;
	}
yy33:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'o': goto yy52;
		default: goto yy26;
	}
yy34:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'i': goto yy53;
		default: goto yy26;
	}
yy35:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'r': goto yy54;
		case 'u': goto yy55;
		default: goto yy26;
	}
yy36:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'r': goto yy56;
		default: goto yy26;
	}
yy37:
	++cursor;
#line 67 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::BeginBrace; }
#line 409 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy38:
	++cursor;
#line 77 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Or; }
#line 414 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy39:
	++cursor;
#line 68 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::EndBrace; }
#line 419 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy40:
	++cursor;
#line 81 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::NotEqual; }
#line 424 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy41:
	yych = *++cursor;
	switch (yych) {
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy25;
		default: goto yy42;
	}
yy42:
	cursor = marker;
	switch (yyaccept) {
		case 0: goto yy2;
		case 1: goto yy27;
		case 2: goto yy61;
		case 3: goto yy64;
		case 4: goto yy67;
		case 5: goto yy78;
		case 6: goto yy82;
		case 7: goto yy89;
		case 8: goto yy92;
		case 9: goto yy94;
		case 10: goto yy96;
		default: goto yy98;
	}
yy43:
	++cursor;
#line 79 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::LessThanOrEqual; }
#line 503 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy44:
	++cursor;
#line 80 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::EqualEqual; }
#line 508 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy45:
	++cursor;
#line 83 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::GreaterThanOrEqual; }
#line 513 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy46:
	yych = *++cursor;
	switch (yych) {
		case ':': goto yy57;
		default: goto yy42;
	}
yy47:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'o': goto yy58;
		default: goto yy26;
	}
yy48:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 't': goto yy59;
		default: goto yy26;
	}
yy49:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'l': goto yy60;
		default: goto yy26;
	}
yy50:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'l': goto yy62;
		default: goto yy26;
	}
yy51:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 't': goto yy63;
		default: goto yy26;
	}
yy52:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'd': goto yy65;
		default: goto yy26;
	}
yy53:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'l': goto yy66;
		default: goto yy26;
	}
yy54:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'i': goto yy68;
		default: goto yy26;
	}
yy55:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'b': goto yy69;
		default: goto yy26;
	}
yy56:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'u': goto yy70;
		default: goto yy26;
	}
yy57:
	yych = *++cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy25;
		default: goto yy42;
	}
yy58:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'l': goto yy71;
		default: goto yy26;
	}
yy59:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'e': goto yy72;
		default: goto yy26;
	}
yy60:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy61;
	}
yy61:
#line 52 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::NilType; }
#line 757 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy62:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 's': goto yy73;
		default: goto yy26;
	}
yy63:
	yyaccept = 3;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy64;
	}
yy64:
#line 58 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Let; }
#line 839 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy65:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'u': goto yy74;
		default: goto yy26;
	}
yy66:
	yyaccept = 4;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy67;
	}
yy67:
#line 51 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Nil; }
#line 921 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy68:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'v': goto yy75;
		default: goto yy26;
	}
yy69:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'l': goto yy76;
		default: goto yy26;
	}
yy70:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'e': goto yy77;
		default: goto yy26;
	}
yy71:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'e': goto yy79;
		default: goto yy26;
	}
yy72:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'g': goto yy80;
		default: goto yy26;
	}
yy73:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'e': goto yy81;
		default: goto yy26;
	}
yy74:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'l': goto yy83;
		default: goto yy26;
	}
yy75:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'a': goto yy84;
		default: goto yy26;
	}
yy76:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'i': goto yy85;
		default: goto yy26;
	}
yy77:
	yyaccept = 5;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy78;
	}
yy78:
#line 54 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::True; }
#line 1067 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy79:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'a': goto yy86;
		default: goto yy26;
	}
yy80:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'e': goto yy87;
		default: goto yy26;
	}
yy81:
	yyaccept = 6;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy82;
	}
yy82:
#line 55 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::False; }
#line 1157 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy83:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'e': goto yy88;
		default: goto yy26;
	}
yy84:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 't': goto yy90;
		default: goto yy26;
	}
yy85:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'c': goto yy91;
		default: goto yy26;
	}
yy86:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'n': goto yy93;
		default: goto yy26;
	}
yy87:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'r': goto yy95;
		default: goto yy26;
	}
yy88:
	yyaccept = 7;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy89;
	}
yy89:
#line 59 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Module; }
#line 1271 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy90:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
		case 0x00: goto yy27;
		case 'e': goto yy97;
		default: goto yy26;
	}
yy91:
	yyaccept = 8;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy92;
	}
yy92:
#line 60 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Public; }
#line 1353 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy93:
	yyaccept = 9;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy94;
	}
yy94:
#line 56 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::BooleanType; }
#line 1427 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy95:
	yyaccept = 10;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy96;
	}
yy96:
#line 53 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::IntegerType; }
#line 1501 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy97:
	yyaccept = 11;
	yych = *(marker = ++cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy98;
	}
yy98:
#line 61 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::Private; }
#line 1575 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
yy99:
#line 90 "/home/cadence/projects/Mint/source/scan/Scanner.re"
	{ UpdateLocation(); return Token::End; }
#line 1579 "/home/cadence/projects/Mint/source/scan/Scanner.cpp"
}
#line 91 "/home/cadence/projects/Mint/source/scan/Scanner.re"

  }
}
// NOLINTEND(cppcoreguidelines-avoid-goto)
} // namespace mint